source :rubygems

gem 'sqlite3'
gem 'rails', "~> 3.0.0"
gem "rspec", "~> 2.3.0"
gem "cucumber-rails"
gem 'ruby-debug19'
gem 'infinity_test'
gem 'sunspot_rails'
gem 'capybara'
gem 'formtastic'
gem 'nifty-generators'
gem 'machinist'
gem 'faker'
gem 'will_paginate'
